name: iOS CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:
    inputs:
      deploy_to_testflight:
        description: 'Deploy to TestFlight?'
        required: true
        default: false
        type: boolean

jobs:
  lint:
    name: Code Linting
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Install SwiftLint
      run: brew install swiftlint
    
    - name: Run SwiftLint
      run: swiftlint --reporter github-actions-logging || true
      
  test:
    name: Test
    needs: lint
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Select Xcode
      run: sudo xcode-select --switch /Applications/Xcode.app
      
    - name: Build and Test
      run: |
        xcodebuild -scheme Sample -destination 'platform=iOS Simulator,name=iPhone 14' test | xcpretty
